export type {
  LoginFormData,
  LoginFormErrors,
  SignupFormData,
  SignupFormErrors,
  AuthResponse,
  UserData,
  SessionData,
  ValidatedSession,
  ProjectData,
  LoginState,
  SignupState,
  FeatureItem,
  StepItem,
  FooterLink,
  FooterSection,
} from "@/domain/auth/types";
